// Level maps. Legend:
//  #  wall          .  floor         P  start          c  chip         S  chip socket   E  exit
//  r b y g  keys    R B Y G  doors (green key is never used up)            ?  hint
//  ~  water         &  fire          _  ice            % dirt          < > ^ v  force floors
//  f  flippers      h  fire boots    k  ice skates     x  suction boots   $  block
//  1  bug           2  ball (horizontal)   3  ball (vertical)   t  teeth (chases you)
(function (root) {
  const LEVELS = [
    {
      name: 'First Steps', time: 0,
      hint: 'Grab every computer chip. When they are all collected the socket opens and you can reach the exit.',
      map: [
        '#############',
        '#c....#....c#',
        '#.###.#.###.#',
        '#...c...c...#',
        '###...P...###',
        '#...c.?.c...#',
        '#.###...###.#',
        '#c.........c#',
        '######S######',
        '######E######',
        '#############',
      ],
    },
    {
      name: 'Lock & Key', time: 150,
      hint: 'Keys open doors of the same color. Red, blue and yellow keys are used up; the green key works forever.',
      map: [
        '#################',
        '#c..c#..r..#c..c#',
        '#....R.....B....#',
        '#..y.#..P..#.g..#',
        '######.....######',
        '#c...Y..?..G...c#',
        '#..b.#.....#....#',
        '#c...#..S..#...c#',
        '########E########',
        '#################',
      ],
    },
    {
      name: 'Elements', time: 100,
      hint: 'Flippers let you swim through water. Fire boots let you walk on fire.',
      map: [
        '###############',
        '#P...~~~..&&&c#',
        '#.f?.~~~..&&&.#',
        '#....~~~..&&&c#',
        '#.c..~~~.h&&&.#',
        '#....~~~..&&&c#',
        '#############S#',
        '#############E#',
        '###############',
      ],
    },
    {
      name: 'Block Party', time: 150,
      hint: 'Push blocks into water to fill it with dirt. Step on dirt to clear it.',
      map: [
        '###############',
        '#.....#~~~..c.#',
        '#..$..#~~~.c..#',
        '#P?.$..~~~..c.#',
        '#..$..#~~~.c..#',
        '#.....#~~~....#',
        '###########S###',
        '###########E###',
        '###############',
      ],
    },
    {
      name: 'Slip & Slide', time: 150,
      hint: 'Ice is slippery! You slide until you reach solid ground, and bounce off walls.',
      map: [
        '#############',
        '#P?._____.c.#',
        '#..#_____#..#',
        '#.____c____.#',
        '#.__#___#__.#',
        '#.____c____.#',
        '#..#_____#..#',
        '#.c._____...#',
        '######S######',
        '######E######',
        '#############',
      ],
    },
    {
      name: 'Conveyor', time: 150,
      hint: 'Force floors push you along. You can step off them sideways. Suction boots make you immune.',
      map: [
        '###############',
        '#P...?#...#..c#',
        '#.....v...^...#',
        '#..c..v.c.^.x.#',
        '#.....v...^...#',
        '#>>>>>>>>>>>>>#',
        '#.............#',
        '#c....<<<<<..c#',
        '#######S#######',
        '#######E#######',
        '###############',
      ],
    },
    {
      name: 'Shafts', time: 100,
      hint: 'Monsters are deadly. Watch their rhythm and time your moves!',
      map: [
        '##################',
        '###c###c###c######',
        '#P?............SE#',
        '###.###.###.######',
        '###3###.###.######',
        '###.###3###.######',
        '###.###.###3######',
        '###.###.###.######',
        '##################',
      ],
    },
    {
      name: 'Teeth', time: 150,
      hint: 'The teeth chase you, but they are slow. Keep moving!',
      map: [
        '###############',
        '#P....#.....c.#',
        '#.##.....##...#',
        '#.#c..#.#..c#.#',
        '#....##t##....#',
        '#.#c..#.#..c#.#',
        '#.##.....##...#',
        '#c....#.....c.#',
        '#######S#######',
        '#######E#######',
        '###############',
      ],
    },
    {
      name: 'Key Lime', time: 200,
      hint: '',
      map: [
        '#################',
        '#P..#.....#.....#',
        '#...R.y...#..c..#',
        '#.r.#.....Y.&&&.#',
        '#...#######.&c&.#',
        '#.h.#c___.#.&&&.#',
        '#...B__._.#.....#',
        '#.b.#.___c#..c..#',
        '###########S#####',
        '###########E#####',
        '#################',
      ],
    },
    {
      name: 'Grand Tour', time: 250,
      hint: '',
      map: [
        '###################',
        '#P..#..c..#......c#',
        '#.$.~.....R.vvvvv.#',
        '#...#..2..#.vvcvv.#',
        '#####.....#.~~~~~.#',
        '#c..G..r..#.......#',
        '#.x.#.g...####S####',
        '#c..##########E####',
        '###################',
      ],
    },
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = LEVELS;
  else root.CHIP_LEVELS = LEVELS;
})(this);
